[package]
name = "merak"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pest = "2.6"
pest_derive = "2.6"
z3 = { version = "0.12" }
z3-sys = "0.8"
thiserror = "1.0"
rand = "0.8.5"
